"""fav_food removed

Revision ID: d3c51c83be5b
Revises: 6031edac1314
Create Date: 2024-01-24 21:06:42.709060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c51c83be5b'
down_revision = '6031edac1314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('fav_food')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_food', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
